### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by scholkine** [SeffUwU/TF2-Killfeed-Generator#1]
There are no buttons "KILL!" and "DOMINATE!" buttons anymore.

But they used to be a month ago

**Comment by SeffUwU** [comment]
I've checked on several devices and they seem to be in place..
Could you describe the issue?
What device you're using?
Which browser?

Also a good idea would be to clear browser cache, just to be sure.
Thank you for your feedback.

**Comment by scholkine** [comment]
Sorry for missing your message. I was using mobile, and button didn't
appear because of aspect ratio in vertical orientation. Anyway, it is not
such a problem after rotation

ср, 22 черв. 2022, 23:33 користувач SeffUwU ***@***.***> пише:

**Comment by SeffUwU** [comment]
It's been six months
