### ISSUE TITLE
minor issue but

### ISSUE THREAD

**Issue by spytf2isohot** [SeffUwU/TF2-Killfeed-Generator#2]
![image](https://github.com/user-attachments/assets/a9082753-4906-4962-b9ad-f1266a78ba32)
the kill icons are blurry
dunno if its a thing with my pc but they just are

**Comment by SeffUwU** [comment]
It's because they are low resolution. I ripped them off the wiki xd

**Comment by spytf2isohot** [comment]
damn!
also theres some new kill icons due to zombie infection
if you want I could get images of them for you

**Comment by SeffUwU** [comment]
> damn! also theres some new kill icons due to zombie infection if you want I could get images of them for you

yeah that would be great!

**Comment by spytf2isohot** [comment]
https://drive.google.com/file/d/1y7epAKyj2oY7NHPvUxKQQiXqy7NAI-SW/view?usp=sharing boom

le kill

**Comment by SeffUwU** [comment]
done. 
thanks!
